- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - mas
        - carthage
        - chruby
        - chruby-fish
        - fish
        - tig
        - the_silver_searcher
    
    - name: install homebrew cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - brisk            
        - plex-media-player
        - charles
        - dropbox
        - reveal
        - visual-studio-code
        - cisco-spark
        - franz
        - slack
        - vlc
        - cyberduck
        - iterm2
        - sourcetree
        - wwdc
        - dash
        - macdown
        - spotify